server:
  port: 3001
  contextPath: /
---
spring:
  profiles: local, default
datasource:
  pmoviecollection:
    url: jdbc:mysql://localhost:3306/db_example
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
---
spring:
  profiles: prod
datasource:
  pmoviecollection:
    url: jdbc:mysql://localhost:3306/db_example
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect